apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: us-east4-docker.pkg.dev/qwiklabs-gcp-01-7cf8ec1d3cdc/my-repository/hello-cloudbuild-dev
        image: v1.0
        ports:
        - containerPort: 8080
